In [1]:
import numpy as np
from numpy import linalg
a = np.array([[1,2], 
              [3,4] ,
              
             ])
x = np.array([[5,6], 
              [7,8] ,
              [3,2]
             ])
y = np.array([0,2,5])

In [61]:

x.dot(linalg.inv(x))

LinAlgError: Last 2 dimensions of the array must be square

In [63]:
b = linalg.inv(a)
a.dot(b)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [50]:
a.dot(b)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [51]:
import numpy as np
np.random.seed(42)
n , m , l = [int(i) for i in input().split()]

Z = np.random.rand(n , m , l)

ValueError: not enough values to unpack (expected 3, got 0)

In [64]:
x @ linalg.inv(x.T @ x) @ x.T @ y

array([0.35714286, 1.71428571, 5.07142857])

In [65]:
np.dot(np.dot(x,a).T,np.dot(x,a))

array([[1571, 2334],
       [2334, 3468]])

In [66]:
(x @ a) @ linalg.inv((x @ a).T @ (x @ a)) @ a.T

array([[-0.19047619,  0.22619048],
       [-0.04761905,  0.11904762],
       [ 0.76190476, -0.6547619 ]])

In [57]:
(x ) @ linalg.inv((x).T @ (x)) 

array([[-4. ,  3.5],
       [ 3. , -2.5]])

In [67]:
x.T @ x

array([[ 83,  92],
       [ 92, 104]])

In [3]:
linalg.inv((x @ a).T @ (x @ a))

array([[ 5.16071429, -3.47321429],
       [-3.47321429,  2.33779762]])

In [69]:
linalg.inv(x.T @ x)

LinAlgError: Last 2 dimensions of the array must be square

In [4]:
(x @ a).T

array([[23, 31,  9],
       [34, 46, 14]])

In [8]:
b= a.T @ x.T

In [9]:
np.divide(a.T , b)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 